package fabricaSillas;

public enum ModeloProducto {
	VINTAGE_RETRO,
	COLONIAL,
	RUSTICO,
	CLASICO,
	MODERNO_CONTEMPORANEO,
	NORDICO_ESCANDINAVO_A1,
	NORDICO_ESCANDINAVO_A2,
	DESCANSO,
	DESCANSO_CON_BRAZOS,
	INFANTIL_OVAL,
	INFANTIL_REDONDA,
	EXTERIOR,
	EXTERIOR_CON_BRAZOS,
	JUVENIL_A1,
	JUVENIL_A2,
	INDUSTRIAL_A1,
	INDUSTRIAL_A2;
}
